In [2]:
%pip install textblob

Requirement already satisfied: textblob in c:\users\artil\appdata\local\programs\python\python310\lib\site-packages (0.17.1)
Requirement already satisfied: nltk>=3.1 in c:\users\artil\appdata\local\programs\python\python310\lib\site-packages (from textblob) (3.8.1)
Requirement already satisfied: click in c:\users\artil\appdata\local\programs\python\python310\lib\site-packages (from nltk>=3.1->textblob) (8.1.3)
Requirement already satisfied: joblib in c:\users\artil\appdata\local\programs\python\python310\lib\site-packages (from nltk>=3.1->textblob) (1.2.0)
Requirement already satisfied: regex>=2021.8.3 in c:\users\artil\appdata\local\programs\python\python310\lib\site-packages (from nltk>=3.1->textblob) (2023.6.3)
Requirement already satisfied: tqdm in c:\users\artil\appdata\local\programs\python\python310\lib\site-packages (from nltk>=3.1->textblob) (4.65.0)
Requirement already satisfied: colorama in c:\users\artil\appdata\roaming\python\python310\site-packages (from click->nltk>=3.1->textblob) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.1.2 -> 23.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
import pandas as pd
from textblob import TextBlob

In [4]:
df_reseña = pd.read_csv('D:/Artemio/Proyectos/Proyecto grupal/finalproject/reseñas/reseñas.csv')

In [5]:
df_reseña.head()

,user_id,name,time,rating,text,pics,gmap_id,place,time_resp,resp
0,1.089268e+20,Christopher Thomas Constantino,2021-06-12 23:27:17.434,4,Great pet friendly place on the American River...,[{'url': ['https://lh5.googleusercontent.com/p...,0x809a55833fbe05ad:0xee6507787fb6a26c,California,2021-06-15 14:39:44.860,Thank you for the review and photos Christophe...
1,1.147835e+20,Valley Girl,2020-11-06 01:35:04.569,5,Beautiful outdoorsy getaway. Kitchenette cotta...,NaN,0x809a55833fbe05ad:0xee6507787fb6a26c,California,2021-01-18 16:55:19.328,Thank you Valley Girl !! Come back again somet...
2,1.158307e+20,John Barringer,2020-11-01 03:06:47.321,5,I was the chef at this evening's wedding. I wa...,NaN,0x809a55833fbe05ad:0xee6507787fb6a26c,California,2020-11-01 02:12:50.230,Thank you John! It means alot to us that you t...
3,1.083060e+20,Missey Iverson,2021-06-08 15:35:00.137,5,I am trying to book a small cabin. Help. 😆,NaN,0x809a55833fbe05ad:0xee6507787fb6a26c,California,2021-06-08 15:56:07.495,Well this is a first 😄 if you are in fact tryi...
4,1.165939e+20,Larry S.,2018-04-09 16:11:16.898,5,My kids and I spent part of last week in Colom...,NaN,0x809a55833fbe05ad:0xee6507787fb6a26c,California,2020-06-18 20:41:34.586,Thank you Larry! Its river time again!

In [6]:
df_reseña.shape

(6088, 10)

In [7]:
def classify_comment(comment):
    if comment is None:
        return 'No message'
    else:
        sentiment = TextBlob(comment).sentiment.polarity
        if sentiment > 0:
            return 'Positive'
        elif sentiment < 0:
            return 'Negative'
        else:
            return 'Neutral'

In [8]:
df_reseña['feeling'] = df_reseña['text'].apply(lambda x: classify_comment(x) if pd.notnull(x) else 'No message')

In [9]:
df_reseña.head()

,user_id,name,time,rating,text,pics,gmap_id,place,time_resp,resp,feeling
0,1.089268e+20,Christopher Thomas Constantino,2021-06-12 23:27:17.434,4,Great pet friendly place on the American River...,[{'url': ['https://lh5.googleusercontent.com/p...,0x809a55833fbe05ad:0xee6507787fb6a26c,California,2021-06-15 14:39:44.860,Thank you for the review and photos Christophe...,Positive
1,1.147835e+20,Valley Girl,2020-11-06 01:35:04.569,5,Beautiful outdoorsy getaway. Kitchenette cotta...,NaN,0x809a55833fbe05ad:0xee6507787fb6a26c,California,2021-01-18 16:55:19.328,Thank you Valley Girl !! Come back again somet...,Positive
2,1.158307e+20,John Barringer,2020-11-01 03:06:47.321,5,I was the chef at this evening's wedding. I wa...,NaN,0x809a55833fbe05ad:0xee6507787fb6a26c,California,2020-11-01 02:12:50.230,Thank you John! It means alot to us that you t...,Positive
3,1.083060e+20,Missey Iverson,2021-06-08 15:35:00.137,5,I am trying to book a small cabin. Help. 😆,NaN,0x809a55833fbe05ad:0xee6507787fb6a26c,California,2021-06-08 15:56:07.495,Well this is a first 😄 if you are in fact tryi...,Negative
4,1.165939e+20,Larry S.,2018-04-09 16:11:16.898,5,My kids and I spent part of last week in Colom...,NaN,0x809a55833fbe05ad:0xee6507787fb6a26c,California,2020-06-18 20:41:34.586,Thank you Larry! Its river time again!,Positive

In [10]:
df_reseña

,user_id,name,time,rating,text,pics,gmap_id,place,time_resp,resp,feeling
0,1.089268e+20,Christopher Thomas Constantino,2021-06-12 23:27:17.434,4,Great pet friendly place on the American River...,[{'url': ['https://lh5.googleusercontent.com/p...,0x809a55833fbe05ad:0xee6507787fb6a26c,California,2021-06-15 14:39:44.860,Thank you for the review and photos Christophe...,Positive
1,1.147835e+20,Valley Girl,2020-11-06 01:35:04.569,5,Beautiful outdoorsy getaway. Kitchenette cotta...,NaN,0x809a55833fbe05ad:0xee6507787fb6a26c,California,2021-01-18 16:55:19.328,Thank you Valley Girl !! Come back again somet...,Positive
2,1.158307e+20,John Barringer,2020-11-01 03:06:47.321,5,I was the chef at this evening's wedding. I wa...,NaN,0x809a55833fbe05ad:0xee6507787fb6a26c,California,2020-11-01 02:12:50.230,Thank you John! It means alot to us that you t...,Positive
3,1.083060e+20,Missey Iverson,2021-06-08 15:35:00.137,5,I am trying to book a small cabin. Help. 😆,NaN,0x809a55833fbe05ad:0xee6507787fb6a26c,California,2021-06-08 15:56:07.495,Well this is a first 😄 if you are in fact tryi...,Negative
4,1.165939e+20,Larry S.,2018-04-09 16:11:16.898,5,My kids and I spent part of last week in Colom...,NaN,0x809a55833fbe05ad:0xee6507787fb6a26c,California,2020-06-18 20:41:34.586,Thank you Larry! Its river time again!,Positive
...,...,...,...,...,...,...,...,...,...,...,...
6083,1.127285e+20,Don Todd,2018-03-20 02:12:33.163,1,NaN,NaN,0x89dfce4984aaa485:0xacbd33cecf7d50d4,New York,NaN,NaN,No message
6084,1.040970e+20,Luc “190falcon” Blanchette,2017-02-05 12:06:51.870,3,NaN,NaN,0x89dfce4984aaa485:0xacbd33cecf7d50d4,New York,NaN,NaN,No message
6085,1.032762e+20,Kathy Reeks,2018-02-26 14:43:08.810,5,NaN,NaN,0x89dfce4984aaa485:0xacbd33cecf7d50d4,New York,NaN,NaN,No message
6086,1.028247e+20,Matthew Gordon,2018-03-20 06:25:39.435,3,NaN,NaN,0x89dfce4984aaa485:0xacbd33cecf7d50d4,New York,NaN,NaN,No message
6087,1.029704e+20,Charlene Cook,2017-10-07 08:14:14.038,1,NaN,NaN,0x89dfce4984aaa485:0xacbd33cecf7d50d4,New York,NaN,NaN,No message

In [11]:
df_reseña['feeling_resp'] = df_reseña['resp'].apply(lambda x: classify_comment(x) if pd.notnull(x) else 'No message')

In [12]:
df_reseña

,user_id,name,time,rating,text,pics,gmap_id,place,time_resp,resp,feeling,feeling_resp
0,1.089268e+20,Christopher Thomas Constantino,2021-06-12 23:27:17.434,4,Great pet friendly place on the American River...,[{'url': ['https://lh5.googleusercontent.com/p...,0x809a55833fbe05ad:0xee6507787fb6a26c,California,2021-06-15 14:39:44.860,Thank you for the review and photos Christophe...,Positive,Positive
1,1.147835e+20,Valley Girl,2020-11-06 01:35:04.569,5,Beautiful outdoorsy getaway. Kitchenette cotta...,NaN,0x809a55833fbe05ad:0xee6507787fb6a26c,California,2021-01-18 16:55:19.328,Thank you Valley Girl !! Come back again somet...,Positive,Neutral
2,1.158307e+20,John Barringer,2020-11-01 03:06:47.321,5,I was the chef at this evening's wedding. I wa...,NaN,0x809a55833fbe05ad:0xee6507787fb6a26c,California,2020-11-01 02:12:50.230,Thank you John! It means alot to us that you t...,Positive,Neutral
3,1.083060e+20,Missey Iverson,2021-06-08 15:35:00.137,5,I am trying to book a small cabin. Help. 😆,NaN,0x809a55833fbe05ad:0xee6507787fb6a26c,California,2021-06-08 15:56:07.495,Well this is a first 😄 if you are in fact tryi...,Negative,Positive
4,1.165939e+20,Larry S.,2018-04-09 16:11:16.898,5,My kids and I spent part of last week in Colom...,NaN,0x809a55833fbe05ad:0xee6507787fb6a26c,California,2020-06-18 20:41:34.586,Thank you Larry! Its river time again!,Positive,Neutral
...,...,...,...,...,...,...,...,...,...,...,...,...
6083,1.127285e+20,Don Todd,2018-03-20 02:12:33.163,1,NaN,NaN,0x89dfce4984aaa485:0xacbd33cecf7d50d4,New York,NaN,NaN,No message,No message
6084,1.040970e+20,Luc “190falcon” Blanchette,2017-02-05 12:06:51.870,3,NaN,NaN,0x89dfce4984aaa485:0xacbd33cecf7d50d4,New York,NaN,NaN,No message,No message
6085,1.032762e+20,Kathy Reeks,2018-02-26 14:43:08.810,5,NaN,NaN,0x89dfce4984aaa485:0xacbd33cecf7d50d4,New York,NaN,NaN,No message,No message
6086,1.028247e+20,Matthew Gordon,2018-03-20 06:25:39.435,3,NaN,NaN,0x89dfce4984aaa485:0xacbd33cecf7d50d4,New York,NaN,NaN,No message,No message
6087,1.029704e+20,Charlene Cook,2017-10-07 08:14:14.038,1,NaN,NaN,0x89dfce4984aaa485:0xacbd33cecf7d50d4,New York,NaN,NaN,No message,No message

In [15]:
df_reseña.to_csv('D:/Artemio/Proyectos/Proyecto grupal/finalproject/reseñas/reseñas.csv', index=False)